package br.com.apidynamodb.models

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable

@DynamoDBTable(tableName = "Product")
data class ProductModel(

    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    val id : Int = 0,

    @DynamoDBAttribute
    val msrp: String = "",

    @DynamoDBAttribute
    val cost : String = ""
) {

}